# Generated by Django 4.0.2 on 2022-09-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
