# Generated by Django 4.0.2 on 2022-09-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_about_us_phone_alter_about_us_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
