# Generated by Django 4.0.2 on 2022-09-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('remove', models.BooleanField(default=False, editable=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
