# Generated by Django 4.0.2 on 2022-09-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='novena',
            name='eight_day',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novena',
            name='fifth_day',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novena',
            name='first_day',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novena',
            name='forth_day',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novena',
            name='ninth_day',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novena',
            name='second_day',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novena',
            name='seventh_day',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novena',
            name='six_day',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novena',
            name='third_day',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
