# Generated by Django 4.0.2 on 2022-09-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_novena_eight_day_novena_fifth_day_novena_first_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novena',
            old_name='eight_day',
            new_name='eighth_day',
        ),
        migrations.AddField(
            model_name='novena',
            name='additional',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='additional_d',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='additional_dd',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='additional_ddd',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='additional_ee',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='additional_ff',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='additional_gg',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='additional_hh',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='additional_ii',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_a',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_aa',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_b',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_bb',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_c',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_cc',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_ddd',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_ee',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_ff',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_gg',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_hh',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_ii',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='description1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='description2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='description3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='description4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='description5',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='description6',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='description7',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='description8',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='description9',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='other_description1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='other_description2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='other_description3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='other_description4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='other_description5',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='other_description6',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='other_description7',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='other_description8',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='other_description9',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='prayers1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='prayers2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='prayers3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='prayers4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='prayers5',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='prayers6',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='prayers7',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='prayers8',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='prayers9',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='title1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='title2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='title3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='title4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='title5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='title6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='title7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='title8',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='title9',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
