# Generated by Django 4.0.2 on 2022-09-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_novena_additional_d_alter_novena_additional_dd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novena',
            name='additional',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
