# Generated by Django 4.0.2 on 2022-09-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_novena_additional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novena',
            old_name='closing_prayer_ddd',
            new_name='closing_prayer_da',
        ),
        migrations.RenameField(
            model_name='novena',
            old_name='closing_prayer_ee',
            new_name='closing_prayer_db',
        ),
        migrations.RenameField(
            model_name='novena',
            old_name='closing_prayer_ff',
            new_name='closing_prayer_dc',
        ),
        migrations.RenameField(
            model_name='novena',
            old_name='closing_prayer_gg',
            new_name='closing_prayer_ea',
        ),
        migrations.RenameField(
            model_name='novena',
            old_name='closing_prayer_hh',
            new_name='closing_prayer_eb',
        ),
        migrations.RenameField(
            model_name='novena',
            old_name='closing_prayer_ii',
            new_name='closing_prayer_ec',
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_fa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_fb',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_fc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_ga',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_gb',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_gc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_ha',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_hb',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_hc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_ia',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_ib',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='novena',
            name='closing_prayer_ic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
