# Generated by Django 4.0.2 on 2022-09-21 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_closing_prayer_ddd_novena_closing_prayer_da_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='novena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novena_comments', to='blog.novena'),
        ),
    ]
