# Generated by Django 4.0.2 on 2022-09-21 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_comment_novena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='novena',
        ),
        migrations.CreateModel(
            name='NovenaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_body', models.TextField(max_length=10000)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('novena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novena_comments', to='blog.novena')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
