# Generated by Django 4.0.2 on 2022-09-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_novena_novenacomment_novenas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('eamil', models.EmailField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
    ]
