# Generated by Django 4.0.2 on 2022-09-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_subscribeduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribeduser',
            old_name='eamil',
            new_name='email',
        ),
    ]
