# Generated by Django 4.0 on 2023-06-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_novena_additional_remove_novena_additional_d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daysofnovena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.novena')),
            ],
        ),
    ]
