# Generated by Django 4.0 on 2023-06-04 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_daysofnovena'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysofnovena',
            name='day1',
            field=models.TextField(default='this', max_length=5000),
        ),
        migrations.AddField(
            model_name='daysofnovena',
            name='day2',
            field=models.TextField(default='this', max_length=5000),
        ),
        migrations.AddField(
            model_name='daysofnovena',
            name='day3',
            field=models.TextField(default='this', max_length=5000),
        ),
        migrations.AddField(
            model_name='daysofnovena',
            name='day4',
            field=models.TextField(default='this', max_length=5000),
        ),
        migrations.AddField(
            model_name='daysofnovena',
            name='day5',
            field=models.TextField(default='this', max_length=5000),
        ),
        migrations.AddField(
            model_name='daysofnovena',
            name='day6',
            field=models.TextField(default='this', max_length=5000),
        ),
        migrations.AddField(
            model_name='daysofnovena',
            name='day7',
            field=models.TextField(default='this', max_length=5000),
        ),
        migrations.AddField(
            model_name='daysofnovena',
            name='day8',
            field=models.TextField(default='this', max_length=5000),
        ),
        migrations.AddField(
            model_name='daysofnovena',
            name='day9',
            field=models.TextField(default='this', max_length=5000),
        ),
        migrations.AlterField(
            model_name='daysofnovena',
            name='novena',
            field=models.ForeignKey(default='this', on_delete=django.db.models.deletion.CASCADE, to='blog.novena'),
        ),
    ]
