# Generated by Django 4.0 on 2023-06-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_daysofnovena_day1_alter_daysofnovena_day2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daysofnovena',
        ),
    ]
