# Generated by Django 4.0 on 2023-06-04 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_delete_daysofnovena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.TextField(max_length=5000)),
                ('day2', models.TextField(max_length=5000)),
                ('day3', models.TextField(max_length=5000)),
                ('day4', models.TextField(max_length=5000)),
                ('day5', models.TextField(max_length=5000)),
                ('day6', models.TextField(max_length=5000)),
                ('day7', models.TextField(max_length=5000)),
                ('day8', models.TextField(max_length=5000)),
                ('day9', models.TextField(max_length=5000)),
                ('novena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.novena')),
            ],
        ),
    ]
