# Generated by Django 4.0 on 2023-06-04 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='novena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daysofnovena', to='blog.novena'),
        ),
    ]
