# Generated by Django 4.0 on 2023-06-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_days_novena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailyprayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('prayer', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Medicationfooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('footer', models.TextField(max_length=10000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
