# Generated by Django 4.0 on 2023-06-06 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_dailyprayer_medicationfooter_delete_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprayer',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
