# Generated by Django 4.0 on 2023-06-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_dailyprayer_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribuser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.subscribeduser')),
            ],
        ),
        migrations.DeleteModel(
            name='Medicationfooter',
        ),
    ]
