# Generated by Django 4.0 on 2023-06-09 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_unsubscribe_delete_medicationfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscribe',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
