# Generated by Django 4.0 on 2023-06-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_unsubscribe_unsubscribe_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribeduser',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Unsubscribe',
        ),
    ]
