# Generated by Django 4.0 on 2023-06-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_subscribeduser_subscribed_delete_unsubscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayers',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='prayers',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
