# Generated by Django 4.0 on 2023-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_prayers_options_prayers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayers',
            name='intro',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
