# Generated by Django 4.0 on 2023-06-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_prayers_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(upload_to='media/')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
