# Generated by Django 4.0 on 2023-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_prayerintro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayers',
            name='intro',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
