# Generated by Django 4.0 on 2023-06-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_prayers_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayers',
            name='intro',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
