# Generated by Django 4.0 on 2023-06-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_prayers_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stationofcross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_prayer', models.TextField(max_length=10000)),
                ('title', models.CharField(max_length=100, null=True)),
                ('station_body', models.TextField(max_length=20000)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('image', models.ImageField(upload_to='station/')),
                ('closing_prayer', models.TextField(max_length=10000)),
            ],
        ),
    ]
