# Generated by Django 4.0 on 2023-06-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_stationofcross'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station_open_closing_prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_prayers', models.CharField(max_length=100, null=True)),
                ('closing_prayers', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='StationsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('station_img', models.ImageField(upload_to='station/')),
            ],
        ),
        migrations.CreateModel(
            name='Stationsprayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('prayer', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stationofcross',
            name='closing_prayer',
        ),
        migrations.RemoveField(
            model_name='stationofcross',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stationofcross',
            name='opening_prayer',
        ),
        migrations.AddField(
            model_name='stationofcross',
            name='stationimages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.stationsimages'),
        ),
    ]
