# Generated by Django 4.0 on 2023-06-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_station_open_closing_prayer_opening_prayers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station_open_closing_prayer',
            name='opening_prayers',
            field=models.TextField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='stationsprayers',
            name='prayer',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
