# Generated by Django 4.0 on 2023-06-11 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_station_open_closing_prayer_opening_prayers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationofcross',
            name='letuspray',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.stationsprayers'),
        ),
    ]
