# Generated by Django 4.0 on 2023-06-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_stationofcross_letuspray'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsprayers',
            name='hymn',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
