# Generated by Django 4.0 on 2023-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_stationsprayers_words_of_our_lord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationofcross',
            name='station_body',
        ),
        migrations.AddField(
            model_name='stationsprayers',
            name='from_pro',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
