# Generated by Django 4.0 on 2023-06-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_remove_stationofcross_station_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsprayers',
            name='heading',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
