# Generated by Django 4.0 on 2023-06-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_stationsprayers_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsprayers',
            name='we_ador',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
