# Generated by Django 4.0 on 2023-06-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_stationsprayers_we_ador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationsprayers',
            name='we_ador',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
