# Generated by Django 4.0 on 2023-06-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_station_open_closing_prayer_sation_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='station_open_closing_prayer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
