# Generated by Django 4.0 on 2023-06-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_station_open_closing_prayer_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningPrayerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('station_img', models.ImageField(null=True, upload_to='station/')),
            ],
        ),
        migrations.AddField(
            model_name='station_open_closing_prayer',
            name='image',
            field=models.ImageField(null=True, upload_to='station/'),
        ),
    ]
