# Generated by Django 4.0 on 2023-06-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_openingprayerimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station_open_closing_prayer',
            name='opening_prayer_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.openingprayerimages'),
        ),
    ]
