# Generated by Django 4.0 on 2023-06-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_station_open_closing_prayer_opening_prayer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station_open_closing_prayer',
            name='image',
        ),
    ]
