# Generated by Django 4.0 on 2023-06-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_remove_station_open_closing_prayer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationofcross',
            name='number_of_stations',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
