# Generated by Django 4.0 on 2023-06-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_newsletter_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_blog',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
