# Generated by Django 4.0 on 2023-06-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_newsletter_station_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='station_img',
            new_name='news_img',
        ),
    ]
