# Generated by Django 5.0 on 2024-07-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0055_gallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={"ordering": ["-date"]},
        ),
    ]
