# Generated by Django 5.0 on 2024-09-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0056_alter_gallery_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="novena",
            options={"ordering": ["-post_date"]},
        ),
    ]
