# Generated by Django 5.0 on 2024-07-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeApp", "0002_similarfield_author_similarfield_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="similarfield",
            name="bible_verse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
