# Generated by Django 5.0 on 2024-07-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeApp", "0003_similarfield_bible_verse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="focolarepassword",
            options={"ordering": ["-posted_date"]},
        ),
    ]
