# Generated by Django 5.0 on 2024-09-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeApp", "0004_alter_focolarepassword_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=2000)),
                ("post_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
