# Generated by Django 5.0 on 2024-09-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeApp", "0005_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["-post_date"]},
        ),
        migrations.AddField(
            model_name="contact",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
