# Generated by Django 5.0 on 2024-09-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeApp", "0006_alter_contact_options_contact_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sacramental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("usage", models.TextField(blank=True, null=True)),
                ("significance", models.TextField(blank=True, null=True)),
                ("blessing_prayer", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="sacramentals_images/"
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sacramental",
                "verbose_name_plural": "Sacramentals",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SaintOfTheDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("feast_day", models.DateField()),
                ("biography", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="saints_images/"
                    ),
                ),
                ("patronage", models.CharField(blank=True, max_length=255, null=True)),
                ("quotes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Saint of the Day",
                "verbose_name_plural": "Saints of the Day",
                "ordering": ["feast_day"],
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["read"]},
        ),
    ]
