# Generated by Django 5.0 on 2024-09-20 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeApp", "0007_sacramental_saintoftheday_alter_contact_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sacramental",
            name="blessing_prayer",
        ),
        migrations.RemoveField(
            model_name="sacramental",
            name="category",
        ),
        migrations.RemoveField(
            model_name="sacramental",
            name="significance",
        ),
        migrations.RemoveField(
            model_name="sacramental",
            name="usage",
        ),
    ]
